### ISSUE TITLE
发现一个问题

### ISSUE THREAD

**Issue by xiaohao890809** [wenmingvs/WeiBo#12]
我下载完运行后，注册和登陆按钮点击了啥反应都没有呢？是不是点击事件忘记加了呢？

**Comment by wenmingvs** [comment]
更新到最新版本。Bug已经修复

**Comment by xiaohao890809** [comment]
嗯嗯，可以close了，^_^

**Comment by xiaohao890809** [comment]
openLoginWebView 方法怎么还是无法触发呢？奇怪

**Comment by wenmingvs** [comment]
Bug已经紧急修复

实在抱歉，我之前一直都是在Android6.0的设备上做调试，点击是没问题的。刚才调用了一台4.0的设备看下，确实没办法点击。确实是我疏忽了，最近都在重构代码，加新功能，测试上忽略了很多。后面我会充分做好测试，Realse一个稳定版本，供大家体验。

**Comment by xiaohao890809** [comment]
我试了下，这个是TextView，加一个属性android:clickable="true"就可以，但是登陆成功后奔溃了

**Comment by xiaohao890809** [comment]
我试了下，这个是TextView，加一个属性android:clickable="true"就可以，但是登陆成功后奔溃了

**Comment by xiaohao890809** [comment]
我试了下，这个是TextView，加一个属性android:clickable="true"就可以，但是登陆成功后奔溃了

**Comment by wenmingvs** [comment]
能把Android  Studio的Log下的Error截图给我看下嘛？

**Comment by xiaohao890809** [comment]
抱歉图片长传不了，贴代码了：
05-16 18:06:57.308 18693-18693/com.wenming.weiswift E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      java.lang.NumberFormatException: Invalid long: "1735838740&scope=friendships_groups_read%2Cfriendships_groups_write%2Cdirect_messages_read"
                                                                          at java.lang.Long.invalidLong(Long.java:125)
                                                                          at java.lang.Long.parse(Long.java:362)
                                                                          at java.lang.Long.parseLong(Long.java:353)
                                                                          at java.lang.Long.parseLong(Long.java:319)
                                                                          at java.lang.Long.valueOf(Long.java:477)
                                                                          at com.wenming.weiswift.mvp.presenter.imp.HomeFragmentPresentImp.refreshUserName(HomeFragmentPresentImp.java:46)
                                                                          at com.wenming.weiswift.ui.login.fragment.home.HomeFragment$1.run(HomeFragment.java:71)
                                                                          at android.os.Handler.handleCallback(Handler.java:615)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                          at android.os.Looper.loop(Looper.java:137)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:4950)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:511)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:997)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)
                                                                          at dalvik.system.NativeStart.main(Native Method)

**Comment by xiaohao890809** [comment]
update的一个你的代码就又好了

**Comment by wenmingvs** [comment]
应该是服务器返回的token有问题，有时候会增加scope字段，有时候又没有，导致我客户端这边出现问题。我修复这个问题了。这个Bug比较隐藏，一般要登录多个帐号才会出现。谢谢你的提醒
